# WAP to accept marks of 6 students and display them in a sorted manner
marks=[]
S1= int(input("Enter marks of S1:"))
marks.append(S1)
S2= int(input("Enter marks of S2:"))
marks.append(S2)
S3= int(input("Enter marks of S3:"))
marks.append(S3)
S4= int(input("Enter marks of S4:"))
marks.append(S4)
S5= int(input("Enter marks of S5:"))
marks.append(S5)
S6= int(input("Enter marks of S6:"))
marks.append(S6)
# print(marks.sort())
# print(marks)
# sorted= marks.sort()
# print(sorted)
marks.sort()
print(marks)