# WAP to store 7 fruits entered by user in list
fruits=[]
fruit1= input("Enter first fruit:")
fruits.append(fruit1)
fruit2= input("Enter second fruit:")
fruits.append(fruit2)
fruit3= input("Enter third fruit:")
fruits.append(fruit3)
fruit4= input("Enter fourth fruit:")
fruits.append(fruit4)
fruit5= input("Enter fifth fruit:")
fruits.append(fruit5)
fruit6= input("Enter sixth fruit:")
fruits.append(fruit6)
fruit7= input("Enter seventh fruit:")
fruits.append(fruit7)
print(fruits)