#WAP to input  eight numbers from the user and display all the unique numbers(once).
s= set()
n= input("Enter the number:")
s.add(int(n))
n= input("Enter the number:")
s.add(int(n))
n= input("Enter the number:")
s.add(int(n))
n= input("Enter the number:")
s.add(int(n))
n= input("Enter the number:")
s.add(int(n))
n= input("Enter the number:")
s.add(int(n))
n= input("Enter the number:")
s.add(int(n))
n= input("Enter the number:")
s.add(int(n))
print("The set is:",s)
